name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore and build
        run: |
          dotnet restore
          dotnet build

      - name: login to dockerhub
        run: docker login -u ${{secrets.USER_NAME}} -P ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t mikaeljonsson1/kyh-docker-example .
          docker push mikaeljonsson1/kyh-docker-example
